# dev prod
mysql:
  host: rm-uf6q551p64vcy1e6h2o.mysql.rds.aliyuncs.com
  port: 3306
  user: slsl_techadmin
  password: 30SlProd*!#@
  db_name: slslgwzhxt

mongodb:
  host: dds-uf6e7d1d0624a2741792-pub.mongodb.rds.aliyuncs.com
  port: 3717
  user: gwzhxt
  password: g2w3z%h#x8t
  db_name: gwzhxtback
  collection: monitor_data


neo4j:
  host: 10.10.6.55
  port: 7474
  user: neo4j
  password: 123456
  import_dir: /usr/data


kafka:
  servers: ['10.10.6.53:9092', '10.10.6.54:9092', '10.10.6.55:9092']
  topic: 'event_test'
  group_id: 'new_consumer'
  enable_auto_commit: True
  auto_offset_reset: "latest"
  auto_commit_interval_ms: 5000
  partition_seq: 0
  offset_start: 0